# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         HTTP-Parser
version:      0.04
version_from: Parser.pm
installdirs:  site
requires:
    HTTP::Request:                 0
    HTTP::Response:                0
    URI:                           0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
